name: Update Helm chart for staging and production main

on:
  release:
    types: [published]

env:
  PROJECT: assess
  ECR_URI: ${{ secrets.AWS_ECR_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com

jobs:
  update-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2.0.6
        with:
          app-id: ${{ secrets.CICD_APP_ID }}
          private-key: ${{ secrets.CICD_APP_PKEY }}
          owner: ${{ github.repository_owner }}
          repositories: "helm-charts"

      - name: Checkout helm-charts repo
        uses: actions/checkout@v4
        with:
          repository: nhsleadership/helm-charts
          token: ${{ steps.app-token.outputs.token }}

      - name: update tags in Helm chart
        uses: mikefarah/yq@v4.42.1
        with:
          cmd: |
            yq e -i '.image.tag = "main-${{ github.sha }}"' charts/assess/values.yaml
            yq e -i '.appVersion = "${{ github.event.release.tag_name }}"' charts/assess/Chart.yaml
            yq e -i '.version |= (split(".") | .[-1] |= ((. tag = "!!int") + 1) | join("."))' charts/assess/Chart.yaml
  
      - name: Push default image tag for Helm chart.
        run: |
          git config --global user.email "${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"
          git config --global user.name "${{ steps.app-token.outputs.app-slug }}[bot]"
          git commit -am 'assess: updating to ${{ github.event.release.tag_name }}'
          git push
